version: "2"
services:
  leader:
    container_name: rethinkleader
    image: rethinkdb
    mem_limit: "450m"
    ports:
      - "127.0.0.1:8080:8080"
    restart: always
  follower:
    image: rethinkdb
    mem_limit: "450m"
    command: rethinkdb --bind all --join rethinkleader
    restart: always
